name: bilibil_video

on:
  schedule:
    - cron: "45 11 * * *" #不是北京时间, 北京时间需要+8
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Run Project
        env:
          COOKIE: ${{ secrets.COOKIE }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TAG_ID: ${{ secrets.TAG_ID }}
          UID: ${{ secrets.UID }}
          PUSHME_KEY: ${{ secrets.PUSHME_KEY }}
        run: npm ci && node index.js
